# theme = "monokai_pro_machine"
# theme = "dark_plus"
theme = "snazzy"
# theme = "hex_lavender"

[editor]
line-number = "relative"
auto-format = false

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'“' = '”'
# ’ is usually an apostrophe
'«' = '»'
'`' = '`'

[keys.normal]
###
### Emergency function bindings
###

# (C-1 through C-0 are free)

###
### By-word movement
###

# Make sure these are kept in sync with their `extend_…` counterparts in [keys.select]

w = "move_prev_sub_word_start"
e = "move_next_sub_word_end"

W = "move_prev_sub_word_end"
E = "move_next_sub_word_start"

s = "move_prev_word_start"
d = "move_next_word_end"

S = "move_prev_word_end"
D = "move_next_word_start"

x = "move_prev_long_word_start"
c = "move_next_long_word_end"

X = "move_prev_long_word_end"
C = "move_next_long_word_start"

## Bumped by by-word movement
##

R = "select_regex" # mnemonic: “regex” (and I never liked `replace_with_yanked` on R anyway; I much preferred vim’s overtype mode)
C-r = "split_selection"

f = "delete_selection" # mnemonic: “f— it”
M = "change_selection" # mnemonic: “munge”

b = "extend_line_below"     # mnemonic: “below”
B = "extend_to_line_bounds" # (select entire line)

C-9 = "copy_selection_on_prev_line"
C-0 = "copy_selection_on_next_line"

# f/t/F/T are getting totally dropped

F = "no_op"

###
### Cursor movement
###

i = "move_visual_line_up"
j = "move_char_left"
k = "move_visual_line_down"
l = "move_char_right"

## Bumped by cursor movement
##

t = "insert_mode"          # mnemonic: “type”
T = "insert_at_line_start" # mnemonic: like i/I

h = "no_op"
H = "no_op"
I = "no_op"

###
### Page up/page down
###

C-w = "page_cursor_half_up"
C-e = "page_cursor_half_down"

C-s = "page_cursor_up"
C-d = "page_cursor_down"

C-x = "page_up"
C-c = "page_down"

###
### Jumplist
###

C-o = "no_op"
C-8 = "save_selection"
C-i = "jump_backward"
C-k = "jump_forward"
# ␣j opens the jumplist picker still

[keys.select]

###
### By-word selection
###

w = "extend_prev_sub_word_start"
e = "extend_next_sub_word_end"

W = "extend_prev_sub_word_end"
E = "extend_next_sub_word_start"

s = "extend_prev_word_start"
d = "extend_next_word_end"

S = "extend_prev_word_end"
D = "extend_next_word_start"

x = "extend_prev_long_word_start"
c = "extend_next_long_word_end"

X = "extend_prev_long_word_end"
C = "extend_next_long_word_start"

###
### By-character and -line selection
###

i = "extend_visual_line_up"
j = "extend_char_left"
k = "extend_visual_line_down"
l = "extend_char_right"

[keys.insert]
C-a = "goto_line_start"
C-e = "goto_line_end"
