theme = "monokai_pro_machine"

[editor]
line-number = "relative"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'“' = '”'
# ’ is usually an apostrophe
'«' = '»'
'`' = '`'

[keys.insert]
C-a = "goto_line_start"
C-e = "goto_line_end"
